name: 问题反馈 (Bug Feedback)
description: 描述你所遇到的bug (Describe the bug you encountered)
title: "问题反馈 (Bug)："
type: bug
body:
  - type: markdown
    attributes:
      value: |
        请使用最新的测试版反馈bug，在反馈前先在issue中搜索，不要重复反馈。 (Please use the latest beta version to report bugs. Search the issues before reporting to avoid duplicates.)
        ⚠️ 警告：未按本模板填写或缺少关键信息的 Issue 将被直接关闭。  
        ⚠️ Warning: Issues not following this template or missing key information will be closed.
  - type: textarea
    attributes:
      label: 问题描述 (Problem Description)
      description: 请提供一个清晰而简明的问题描述。 (Please provide a clear and concise description of the problem.)
      placeholder: 问题描述 (Problem Description)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤 (Steps to Reproduce)
      description: 请提供复现该问题所需的具体步骤。 (Please provide the specific steps required to reproduce the issue.)
      placeholder: 复现步骤 (Steps to Reproduce)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期行为 (Expected Behavior)
      description: 请描述你期望的正确行为或结果。 (Please describe the correct behavior or result you expect.)
      placeholder: 预期行为 (Expected Behavior)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 系统信息 (System Information)
      description: 请提供关于您的环境的详细信息，包括操作系统、WebView版本等。 (Please provide detailed information about your environment, including operating system, WebView version, etc.)
      placeholder: 系统信息 (System Information)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 相关截图或日志 (Relevant Screenshots or Logs)
      description: 如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。 (If available, please provide relevant screenshots, error logs, or other information that may help resolve the issue.)
      placeholder: 相关截图或日志 (Relevant Screenshots or Logs)
    validations:
      required: false
